#### 目录介绍
- 01.思考一个问题
- 02.先看一个实验
- 03.异常处理耗时测试
- 04.try…catch在for循环外面或者里面



### 01.思考一个问题
- try..catch..到底影响性能吗？
    - 如果没有出现异常不影响，如果频繁出现异常则是影响性能的。
- 从性能角度来审视一下 Java 的异常处理机制，这里有两个可能会相对昂贵的地方：
    - try-catch 代码段会产生额外的性能开销，或者换个角度说，它往往会影响 JVM 对代码进行优化，所以建议仅捕获有必要的代码段。尽量不要一个大的 try 包住整段的代码；与此同时，利用异常控制代码流程，也不是一个好主意，远比我们通常意义上的条件语句（if/else、switch）要低效。
    - Java 每实例化一个 Exception，都会对当时的栈进行快照，这是一个相对比较重的操作。如果发生的非常频繁，这个开销可就不能被忽略了。





### 09.问题分析与思考
- 先来看一个题目，看一下A和B有何区别，哪一个性能更好一些？为什么？
    - A代码
    ```
    try {
        for(int i = 0; i < max; i++) {
            String myString = ...;
            float myNum = Float.parseFloat(myString);
            myFloats[i] = myNum;
        }
    } catch (NumberFormatException ex) {
        return null;
    }
    ```
    - B代码
    ```
    for(int i = 0; i < max; i++) {
        String myString = ...;
        try {
            float myNum = Float.parseFloat(myString);
        } catch (NumberFormatException ex) {
            return null;
        }
        myFloats[i] = myNum;
    }
    ```
- A和B的区别
    - 其实在功能上明显有区别，一个for循环中出现一个异常就终止，另一个则是会很负责任的把它全部跑完，但问题不是问功能，而是问性能上的区别。
- 性能问题分析
    - 性能无非就是看 空间消耗，时间消耗，想当然就觉得try……catch重复执行了这么多次肯定比只执行了一次跑得肯定慢，空间消耗肯定更大。好吧，哥承认完全不了解其中的工作原理。
- 讨论的结果是
    - 在没有抛出异常的情况下，性能完全没区别。[博客](https://github.com/yangchong211/YCBlogs)
- 原因分析
    - 类会跟随一张 异常表（exception table），每一个try……catch都会在这个表里添加行记录，每一个记录都有4个信息（try catch的开始地址，结束地址，异常的处理起始位，异常类名称）。
    - 当代码在运行时抛出了异常时，首先拿着抛出位置到异常表中查找是否可以被catch（例如看位置是不是处于任何一栏中的开始和结束位置之间），如果可以则跑到异常处理的起始位置开始处理，如果没有找到则原地return，并且copy异常的引用给父调用方，接着看父调用的异常表。。。以此类推。
    - 异常如果没发生，也就不会去查表，也就是说你写不写try catch 也就是有没有这个异常表的问题，如果没有发生异常，写try catch对性能是木有消耗的，所以不会让程序跑得更慢。try 的范围大小其实就是异常表中两个值（开始地址和结束地址）的差异而已，也是不会影响性能的。



### 02.先看一个实验
- 随便写一个简单的程序
    ```java
    public class Test {
        public static void main(String[] args) {
            int a = 0,b=2;
            try {
                a = b/0;
            }catch (Exception e){
                a = 1;
            }
        }
    }
    ```
- 看一下字节码指令过程：
    ```
     public static void main(java.lang.String[]);
        descriptor: ([Ljava/lang/String;)V
        flags: (0x0009) ACC_PUBLIC, ACC_STATIC
        Code:
          stack=2, locals=4, args_size=1
             0: iconst_0        push 0
             1: istore_1        pop并保存到局部变量1
             2: iconst_2       push 2
             3: istore_2       pop并保存到局部变量2
             4: iload_2        从局部变量里拿出并push
             5: iconst_0        push 0 
             6: idiv          栈顶两数相除
             7: istore_1
             8: goto          14
            11: astore_3
            12: iconst_1
            13: istore_1
            14: return
          Exception table:
             from    to  target type
                 4     8    11   Class java/lang/Exception
          LineNumberTable:
            line 8: 0
            line 10: 4
            line 13: 8
            line 11: 11
            line 12: 12
            line 14: 14
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
               12       2     3     e   Ljava/lang/Exception;
                0      15     0  args   [Ljava/lang/String;
                2      13     1     a   I
                4      11     2     b   I
          StackMapTable: number_of_entries = 2
            frame_type = 255 /* full_frame */
              offset_delta = 11
              locals = [ class "[Ljava/lang/String;", int, int ]
              stack = [ class java/lang/Exception ]
            frame_type = 2 /* same */
    }
    ```
- 可以看到有个异常表：
    ```
    Exception table:
    from    to  target type
    4     8    11   Class java/lang/Exception
    ```
    - `from`表示`try catch`的开始地址
    - `to`表示`try catch`的结束地址
    - `target`表示异常的处理起始位
    - `type`表示异常类名称
- 代码运行时出错时，会先判断出错位置是否在`from - to`的范围，如果是，则从`target`标志位往下执行，如果没有出错，直接`goto` 到` return`。可以看出，如果代码不出错的话，性能几乎是不受影响的，和正常的代码执行是一样的。



### 03.异常处理耗时测试
- 测试案例代码如下所示
    ```
    public class Test {
        public static void main(String[] args) {
            int a = 0,b=2;
            long startTime = System.nanoTime();
            for (int i = 10; i>0;i--){
                try {
                    a = b/i;
                }catch (Exception e){
                    a = 1;
                }finally {
    
                }
            }
            long runTime = System.nanoTime()-startTime;
            System.out.println(runTime);
        }
    }
    ```
- 只需要把`i>0`改成`i>=0`，程序遍会进行一次异常处理，因为除数不能为0.
    - 在修改之前(无异常运行)，运行的结果是`1133`
    - 修改之后(会出现除数为0异常)，运行结果是`44177`
    - 当然，这个结果和cpu的算力有关，多次运行结果相差无几。
- 结论：
    - **所以，可以看出一旦程序进入到catch里，是非常耗资源的。**



### 04.try…catch在for循环外面或者里面
#### 4.1 try中包含for循环
- 代码如下所示
    ```java
    public class Test {
        public static void main(String[] args) {
            int a = 0,b=2;
            long startTime = System.nanoTime();
            try {
                for (int i = 10; i>=0;i--){
                        a = b/i;
                }
            }catch (Exception e){
                a = 1;
            }finally {
                long runTime = System.nanoTime()-startTime;
                System.out.println(runTime);
            }
        }
    }
    ```
- 运行多次的控制台输出:
    ```
    46820     48708 54749  47953   46820  45310
    ```
- 看一下字节码指令过程
    ``` java
      public static void main(java.lang.String[]);
        descriptor: ([Ljava/lang/String;)V
        flags: (0x0009) ACC_PUBLIC, ACC_STATIC
        Code:
          stack=2, locals=5, args_size=1
             0: iconst_0
             1: istore_1
             2: iconst_2
             3: istore_2
             4: bipush        10
             6: istore_3
             7: iload_3
             8: iflt          21
            11: iload_2
            12: iload_3
            13: idiv
            14: istore_1
            15: iinc          3, -1
            18: goto          7
            21: goto          35
            24: astore_3
            25: iconst_1
            26: istore_1
            27: goto          35
            30: astore        4
            32: aload         4
            34: athrow
            35: return
          Exception table:
             from    to  target type
                 4    21    24   Class java/lang/Exception
                 4    21    30   any
                24    27    30   any
                30    32    30   any
    ```

#### 4.2 try在for循环外面
- 代码如下所示
    ```
    public class Test {
        public static void main(String[] args) {
            int a = 0,b=2;
            long startTime = System.nanoTime();
            for (int i = 10; i>=0;i--){
                try {
                    a = b/i;
                }catch (Exception e){
                    a = 1;
                }finally {
    
                }
            }
                    long runTime = System.nanoTime()-startTime;
                    System.out.println(runTime);
        }
    }
    ```
- 控制台打印：
    ```
    42289  47953  49463  45688  45310
    ```
- 看一下字节码指令过程
    ``` java
      public static void main(java.lang.String[]);
        descriptor: ([Ljava/lang/String;)V
        flags: (0x0009) ACC_PUBLIC, ACC_STATIC
        Code:
          stack=2, locals=6, args_size=1
             0: iconst_0
             1: istore_1
             2: iconst_2
             3: istore_2
             4: bipush        10
             6: istore_3
             7: iload_3
             8: iflt          36
            11: iload_2
            12: iload_3
            13: idiv
            14: istore_1
            15: goto          30
            18: astore        4
            20: iconst_1
            21: istore_1
            22: goto          30
            25: astore        5
            27: aload         5
            29: athrow
            30: iinc          3, -1
            33: goto          7
            36: return
          Exception table:
             from    to  target type
                11    15    18   Class java/lang/Exception
                11    15    25   any
                18    22    25   any
                25    27    25   any
    ```


#### 4.3 得出结论
- **综合实验，我们发现无论从运行时长还是从字节码指令的角度看，它两的性能可以说是一样的。
    - 并没有你感觉到的for循环里放try代码会冗余、资源消耗加倍的问题。**
- 但是从运行逻辑来看，两个是有点不同的
    - 实验三中，因为for在try catch里，所以jvm在编译的时候，把异常处理放在for循环后面才进行。即：`第24-27行`；
    - 实验四中，异常处理是在for循环内部的，即：`第18-22行`。大同小异。






### 其他介绍
#### 01.关于博客汇总链接
- 1.[技术博客汇总](https://www.jianshu.com/p/614cb839182c)
- 2.[开源项目汇总](https://blog.csdn.net/m0_37700275/article/details/80863574)
- 3.[生活博客汇总](https://blog.csdn.net/m0_37700275/article/details/79832978)
- 4.[喜马拉雅音频汇总](https://www.jianshu.com/p/f665de16d1eb)
- 5.[其他汇总](https://www.jianshu.com/p/53017c3fc75d)



#### 02.关于我的博客
- github：https://github.com/yangchong211
- 知乎：https://www.zhihu.com/people/yczbj/activities
- 简书：http://www.jianshu.com/u/b7b2c6ed9284
- csdn：http://my.csdn.net/m0_37700275
- 喜马拉雅听书：http://www.ximalaya.com/zhubo/71989305/
- 开源中国：https://my.oschina.net/zbj1618/blog
- 泡在网上的日子：http://www.jcodecraeer.com/member/content_list.php?channelid=1
- 邮箱：yangchong211@163.com
- 阿里云博客：https://yq.aliyun.com/users/article?spm=5176.100- 239.headeruserinfo.3.dT4bcV
- segmentfault头条：https://segmentfault.com/u/xiangjianyu/articles
- 掘金：https://juejin.im/user/5939433efe88c2006afa0c6e





