### 目录介绍
















#### 3.2 catch语句作用
- 每个catch语句看起来像是一个接收一个且仅接收一个的特殊参数类型的方法。可以在方法块内部处理这个参数，当然有的异常见名知意，因此可以不用处理参数，但并不可以省略。可以有多个catch块与try对应，用来捕获多种不同的异常。异常处理程序必须紧跟在try块之后，当异常被抛出之后，异常处理机制负责搜寻参数与异常类型相匹配的第一个处理程序。然后进入catch块中执行，此时认为异常得到了处理。一旦catch子句结束，则认为处理程序的查找过程结束。
- 只有匹配的catch字句才会执行，在try块内部不同的方法可能会产生相同的异常，而你只需要提供一个针对此类型的异常处理程序。




#### 3.4 如何捕获异常
- 在方法抛出异常之后，运行时系统将转为寻找合适的异常处理器(exception handler)。潜在的异常处理器是异常发生时依次存留在调用栈中的方法的集合。当异常处理器所能处理的异常类型与方法抛出的异常类型相符时，即为合适的异常处理器。
- 运行时系统从发生异常的方法开始，依次回查调用栈中的方法，直至找到含有合适异常处理器的方法并执行。当运行时系统遍历调用栈而未找到合适的异常处理器，则运行时系统终止。同时，意味着Java程序的终止。



#### 3.5 异常注意事项
- 异常注意事项(针对编译期异常)
* a:子类重写父类方法时，子类的方法必须抛出相同的异常或父类异常的子类。(父亲坏了,儿子不能比父亲更坏)
* b:如果父类抛出了多个异常,子类重写父类时,只能抛出相同的异常或者是他的子集,子类不能抛出父类没有的异常
* c:如果被重写的方法没有异常抛出,那么子类的方法绝对不可以抛出异常,如果子类方法内有异常发生,那么子类只能try,不能throws



### 04.异常有哪些分类
- Java的异常(包括Exception和Error)分为可查的异常（checked exceptions）和不可查的异常（unchecked exceptions）。


#### 4.1 可查异常
- **可查异常**（编译器要求必须处置的异常）：正确的程序在运行中，很容易出现的、情理可容的异常状况。可查异常虽然是异常状况，但在一定程度上它的发生是可以预计的，而且一旦发生这种异常状况，就必须采取某种方式进行处理。除了RuntimeException及其子类以外，其他的Exception类及其子类都属于可查异常。这种异常的特点是Java编译器会检查它，也就是说，当程序中可能出现这类异常，要么用try-catch语句捕获它，要么用throws子句声明抛出它，否则编译不会通过。



#### 4.2 不可查异常
- **不可查异常**(编译器不要求强制处置的异常):包括运行时异常（RuntimeException与其子类）和错误（Error）。







### 06.创建自定义异常
#### 6.1 为何用自定义异常
- Java中虽然提供了很多默认的异常类型，但是要想完全覆盖会发生的异常情况显然是不现实的，因此我们可以自定义异常来表示我们预期可能会出现的异常。自定义的形式也非常简单，只需要继承一个相似的异常类即可。建立一个新的异常类最贱的方法就是让编译器为你产生默认构造器，所以这几乎不需要多少代码。




#### 6.2 自定义异常步骤
- 使用Java内置的异常类可以描述在编程时出现的大部分异常情况。除此之外，用户还可以自定义异常。用户自定义异常类，只需继承Exception类即可。
- 在程序中使用自定义异常类，大体可分为以下几个步骤。
    - （1）创建自定义异常类。
    - （2）在方法中通过throw关键字抛出异常对象。
    - （3）如果在当前抛出异常的方法中处理异常，可以使用try-catch语句捕获并处理；否则在方法的声明处通过throws关键字指明要抛出给方法调用者的异常，继续进行下一步操作。
    - （4）在出现异常方法的调用者中捕获并处理异常。


#### 6.3 举一个案例说明
- 自定义异常如下所示：
    ```
    class MyException extends Exception{
    	public MyException(){
    		
    	}
    	public MyException(String msg){
    		super(msg);
    	}
    }
    
    public class FullConstructors {
    	public static void f() throws MyException {
    		System.out.println("Throwing myException from f()");
    		throw new MyException();
    	}
    	public static void g() throws MyException{
    		System.out.println("Throwing myException from g()");
    		throw new MyException("Originated in g()");
    	}
    	public static void main(String[] args) {
    		try{
    			f();
    		}catch(MyException e){
    			e.printStackTrace();
    		}
    		try{
    			g();
    		}catch(MyException e){
    			e.printStackTrace(System.out);
    		}
    	}
    }
    ```
- 在带参数的异常构造器中，显示的调用了其基类的带参构造方法。在catch块的异常处理程序中，调用了在Throwable类（所有异常的基类）声明的printStackTrace方法，该方法如果不带参数则将异常信息也就是从方法调用处到异常产生出的所有方法调用信息打印到标准错误流上，如果带了标准输出流参数，则打印在标准输出流上。区别可以从控制台错误信息的眼神看出。标准错误流更加的引人注目。




### 07.异常的限制说明
- 在覆盖方法的时候，只能抛出在基类方法的异常说明里列出的那些异常。-->这个限制意味着，当基类使用的代码应用到其派生类对象的时候，一样能够工作（包括异常也能工作）。针对构造器以及继承或实现的方法有几点：
- 异常限制对构造器不起作用，构造器可以抛出任何异常，而不必理会基类构造器所抛出的异常。
- 然而基类构造器必须以这样或那样的方式被调用（这里默认构造器将自动被调用）后，派生类构造器的异常说明就必须包含基类构造器的异常说明。
- 派生类构造器不能捕获基类构造器抛出的异常（意味着只能抛出）。通过强制派生类遵守基类方法的异常说明，对象的可替换性得到了保证。
- 派生类的方法可以选择不抛出任何异常，即使它是基类所定义的异常。
- 使用派生类时，编译器只会强制要求捕获该派生类所抛出的异常；但是如果将其向上转型，那么编译器就会要求捕获基类抛出的异常。
- 异常说明本身不属于方法类型的一部分，方法类型是由方法的名字与参数的类型组成的。因此不能基于异常说明来重载方法。
- 一个出现在基类方法的异常说明中的异常，不一定会出现在炮声类方法的异常说明里。与继承中，基类的方法必须出现在派生类里的这种方法相比较，在继承和覆盖的过程中，某个特定方法的“异常说明的接口”是变小了的，与类方法的继承正好相反。




### 08.异常构造器介绍
- 对于构造器被调用时产生的异常，如果简单的使用try...catch...finally结构来处理异常，容易丢失掉异常，并且不能完成finally 内的代码逻辑，或是在不希望的情况下去完成了finally下的逻辑。对于这种情况，需要再用一层 try...catch 来捕获这个容易丢失的异常。
- 如下：
    ```
    public static void main(String[] args) {
        try {
            InputFile in = new InputFile("Cleanup.java");
            try {
                String s;
                int i = 1;
                while ((s = in.getLine()) != null) {
                    // Perform line-by-line processing here...
                }
            } catch (Exception e) {
                System.out.println("Caught Exception in main");
                e.printStackTrace(System.out);
            } finally {
                in.dispose();
            }
        } catch (Exception e) {
            System.out.println("InputFile construction failed");
        }
    }
    ```
- 在构造之后以及创建一个新的 try 块，将构造与其他可能抛出异常的逻辑区分开，这样不会让 finally 内的逻辑被意外执行。这种方式的基本规则是，在创建需要清理的对象之后，立即进入一个 try...finally 语句块。总之在创建构造器的时候，如果容易产生异常，应该仔细考虑如何处理构造器的异常。




### 09.异常链说明
#### 9.1 什么是异常链
- 常常会想要在捕获一个异常后抛出另一个异常,并且希望把原始异常的信息保存下来,这被称为异常链。在JDK1.4以前,程序员必须自己编写代码来保存原始异常的信息。现在所有Throwable的子类在构造器中都可以接受一个 cause(因由)对象作为参数。这个cause就用来表示原始异常,这样通过把原始异常传递给新的异常,使得即使在当前位置创建并抛出了新的异常,也能通过这个异常链追踪到异常最初发生的位置。
- 有趣的是,在 Throwable的子类中,只有三种基本的异常类提供了带caue参数的构造器。它们是Error(用于Java虚拟机报告系统错误)、 Exception以及 Runtimeexception。如果要把其他类型的异常链接起来,应该使用 initCause方法而不是构造器。



#### 9.2 链式异常
- 链式异常用于为异常关联另一个异常，第二个异常用于描述当前异常产生的原因。
    - 例如，某个方法从文件读取数值来作为除法运算的除数，由于发生了I/O错误导致获取到的数值是0，从而导致了ArithmeticException异常。
    - 如果想要让代码调用者知道背后的原因是I/O错误，使用链式异常就可以来处理这种情况以及其他存在多层异常的情况。
- 为了使用链式异常，Throwable有两个构造函数和两个方法用于处理这种情况。两个构造函数：
    ```
    Throwable(Throwable cause)
    Throwable(String message, Throwable cause)
    ```
- cause即是用于指定引发当前异常的背后原因，message则可以用于同时指定异常描述。两个方法：
    ```
    Throwable getCause()
    Throwable initCause(Throwable cause)
    getCause() 方法用来返回引发当前异常的异常，如果不存在背后异常则返回null。
    initCause(Throwable cause)方法将cause和明面上的异常关联到一起，并返回对异常的引用。因此可以在创建异常之后将异常和背后异常关联到一起。但是，背后异常只能设置一次，即initCause(Throwablecause)方法只能调用一次。此外，如果通过构造函数设置了背后异常，也不能再使用该方法来设置背后异常了。
    ```
- 案例展示
    - 例如，参照如下代码：
    ```
    public class Demo {
    	
    	public static void demo(){
    		NullPointerException nullPointerException=new NullPointerException("nullPointer");
    		nullPointerException.initCause(new ArithmeticException("Arithmetic"));
    		throw nullPointerException;
    	}
    
    	public static void main(String[] args) {
    		try {
    			demo();
    		} catch (Exception e) {
    			System.out.println(e.getMessage());
    			System.out.println(e.getCause().getMessage());
    		}
    	}
    }
    ```
- 运行结果是：[博客](https://github.com/yangchong211/YCBlogs)
    ```
    nullPointer
    Arithmetic
    ```
- 链式异常可以包含所需要的任意深度，但是，过长的异常链可能是一种不良的设计。








